export const description: string;
export const disabled: string;
export const error: string;
export const errorMessage: string;
export const focus: string;
export const group: string;
export const input: string;
export const label: string;
export const optional: string;
