export const actions: string;
export const bar: string;
export const divider: string;
export const dividerInvisible: string;
export const icon: string;
export const left: string;
export const subtitle: string;
export const title: string;
export const titleWrapper: string;
