debug:
	cargo build --lib --target wasm32-unknown-unknown
	wasm-bindgen --target web --out-dir ../../packages/main/src/wasm/threads --out-name threads ../../target/wasm32-unknown-unknown/release/wasm_threads.wasm
	wasm-opt -O1 ../../packages/main/src/wasm/threads/threads_bg.wasm -o ../../packages/main/src/wasm/threads/threads_bg.wasm

release:
	cargo build --release --lib --target wasm32-unknown-unknown
	wasm-bindgen --target web --out-dir ../../packages/main/src/wasm/threads --out-name threads ../../target/wasm32-unknown-unknown/release/wasm_threads.wasm
	wasm-opt -Os ../../packages/main/src/wasm/threads/threads_bg.wasm -o ../../packages/main/src/wasm/threads/threads_bg.wasm
